blueprint:
  name: Minoston MR40Z Keypad
  description: |
    This blueprint provides a way to integrate Minoston MR40Z Keypad with Home Assistant.
  domain: automation
  input:
    keypad:
      name: Keypad
      description: Minoston MR40Z keypad
      selector:
        device:
          integration: zwave_js
          manufacturer: Minoston
          model: MR40Z
    scene_001:
      name: Large Top Button
      description: Large top button on the keypad
      default: []
      selector:
        action: {}
    scene_002:
      name: Large Bottom Button
      description: Large bottom button on the keypad
      default: []
      selector:
        action: {}
    scene_003:
      name: Small left Button
      description: Small left button on the keypad
      default: []
      selector:
        action: {}
    scene_004:
      name: Small right Button
      description: Small right button on the keypad
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent
variables:
  device_id: !input keypad
trigger:
  - platform: event
    event_type: zwave_js_value_notification
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      property_key_name: "{{ trigger.event.data.property_key_name }}"
      label: "{{ trigger.event.data.label }}"
      command_class_name: "{{ trigger.event.data.command_class_name }}"
      value: "{{ trigger.event.data.value }}"
  - choose:
      - conditions: "{{ property_key_name == '001' and value == 'KeyPressed' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyPressed2x' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyPressed3x' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyHeldDown' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyReleased' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyPressed' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyPressed2x' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyPressed3x' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '001' and value == 'KeyHeldDown' }}"
        sequence: !input scene_001
      - conditions: "{{ property_key_name == '002' and value == 'KeyPressed' }}"
        sequence: !input scene_002
      - conditions: "{{ property_key_name == '002' and value == 'KeyPressed2x' }}"
        sequence: !input scene_002
      - conditions: "{{ property_key_name == '002' and value == 'KeyPressed3x' }}"
        sequence: !input scene_002
      - conditions: "{{ property_key_name == '002' and value == 'KeyHeldDown' }}"
        sequence: !input scene_002
      - conditions: "{{ property_key_name == '002' and value == 'KeyReleased' }}"
        sequence: !input scene_002
      - conditions: "{{ property_key_name == '003' and value == 'KeyPressed' }}"
        sequence: !input scene_003
      - conditions: "{{ property_key_name == '003' and value == 'KeyPressed2x' }}"
        sequence: !input scene_003
      - conditions: "{{ property_key_name == '003' and value == 'KeyPressed3x' }}"
        sequence: !input scene_003
      - conditions: "{{ property_key_name == '003' and value == 'KeyHeldDown' }}"
        sequence: !input scene_003
      - conditions: "{{ property_key_name == '003' and value == 'KeyReleased' }}"
        sequence: !input scene_003
      - conditions: "{{ property_key_name == '004' and value == 'KeyPressed' }}"
        sequence: !input scene_004
      - conditions: "{{ property_key_name == '004' and value == 'KeyPressed2x' }}"
        sequence: !input scene_004
      - conditions: "{{ property_key_name == '004' and value == 'KeyPressed3x' }}"
        sequence: !input scene_004
      - conditions: "{{ property_key_name == '004' and value == 'KeyHeldDown' }}"
        sequence: !input scene_004
      - conditions: "{{ property_key_name == '004' and value == 'KeyReleased' }}"
        sequence: !input scene_004
